import { IWeatherData } from "../../types/types";

export const defaultWeatherData: IWeatherData = {
    cod: '200',
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1683115200,
            main: {
                temp: 15.28,
                feels_like: 13.28,
                temp_min: 14.85,
                temp_max: 15.28,
                pressure: 1034,
                sea_level: 1034,
                grnd_level: 1022,
                humidity: 16,
                temp_kf: 0.43,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 0,
            },
            wind: {
                speed: 1.42,
                deg: 180,
                gust: 1.57,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-03 12:00:00',
        },
        {
            dt: 1683126000,
            main: {
                temp: 13.05,
                feels_like: 11.04,
                temp_min: 11.83,
                temp_max: 13.05,
                pressure: 1033,
                sea_level: 1033,
                grnd_level: 1022,
                humidity: 24,
                temp_kf: 1.22,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 51,
            },
            wind: {
                speed: 2.54,
                deg: 158,
                gust: 3.3,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-03 15:00:00',
        },
        {
            dt: 1683136800,
            main: {
                temp: 9.55,
                feels_like: 7.91,
                temp_min: 9.55,
                temp_max: 9.55,
                pressure: 1034,
                sea_level: 1034,
                grnd_level: 1022,
                humidity: 34,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 78,
            },
            wind: {
                speed: 3.1,
                deg: 199,
                gust: 5.3,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-03 18:00:00',
        },
        {
            dt: 1683147600,
            main: {
                temp: 7.65,
                feels_like: 5.53,
                temp_min: 7.65,
                temp_max: 7.65,
                pressure: 1033,
                sea_level: 1033,
                grnd_level: 1021,
                humidity: 39,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02n',
                },
            ],
            clouds: {
                all: 17,
            },
            wind: {
                speed: 3.26,
                deg: 215,
                gust: 6.56,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-03 21:00:00',
        },
        {
            dt: 1683158400,
            main: {
                temp: 6.61,
                feels_like: 4.21,
                temp_min: 6.61,
                temp_max: 6.61,
                pressure: 1034,
                sea_level: 1034,
                grnd_level: 1022,
                humidity: 43,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'переменная облачность',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 32,
            },
            wind: {
                speed: 3.36,
                deg: 225,
                gust: 8.57,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-04 00:00:00',
        },
        {
            dt: 1683169200,
            main: {
                temp: 12.07,
                feels_like: 10.14,
                temp_min: 12.07,
                temp_max: 12.07,
                pressure: 1033,
                sea_level: 1033,
                grnd_level: 1022,
                humidity: 31,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'переменная облачность',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 30,
            },
            wind: {
                speed: 5.07,
                deg: 233,
                gust: 7.98,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-04 03:00:00',
        },
        {
            dt: 1683180000,
            main: {
                temp: 16.84,
                feels_like: 15.1,
                temp_min: 16.84,
                temp_max: 16.84,
                pressure: 1032,
                sea_level: 1032,
                grnd_level: 1021,
                humidity: 20,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 23,
            },
            wind: {
                speed: 4.97,
                deg: 225,
                gust: 5.6,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-04 06:00:00',
        },
        {
            dt: 1683190800,
            main: {
                temp: 19.95,
                feels_like: 18.39,
                temp_min: 19.95,
                temp_max: 19.95,
                pressure: 1030,
                sea_level: 1030,
                grnd_level: 1019,
                humidity: 15,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 4.47,
                deg: 234,
                gust: 5.14,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-04 09:00:00',
        },
        {
            dt: 1683201600,
            main: {
                temp: 20.89,
                feels_like: 19.48,
                temp_min: 20.89,
                temp_max: 20.89,
                pressure: 1029,
                sea_level: 1029,
                grnd_level: 1018,
                humidity: 17,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 12,
            },
            wind: {
                speed: 4.15,
                deg: 246,
                gust: 5.31,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-04 12:00:00',
        },
        {
            dt: 1683212400,
            main: {
                temp: 16.25,
                feels_like: 14.61,
                temp_min: 16.25,
                temp_max: 16.25,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1017,
                humidity: 26,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 3.14,
                deg: 217,
                gust: 3.66,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-04 15:00:00',
        },
        {
            dt: 1683223200,
            main: {
                temp: 13.78,
                feels_like: 12,
                temp_min: 13.78,
                temp_max: 13.78,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1017,
                humidity: 30,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 3.42,
                deg: 233,
                gust: 6.34,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-04 18:00:00',
        },
        {
            dt: 1683234000,
            main: {
                temp: 12.16,
                feels_like: 10.4,
                temp_min: 12.16,
                temp_max: 12.16,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1017,
                humidity: 37,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 3.14,
                deg: 252,
                gust: 4.62,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-04 21:00:00',
        },
        {
            dt: 1683244800,
            main: {
                temp: 11.02,
                feels_like: 9.17,
                temp_min: 11.02,
                temp_max: 11.02,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1017,
                humidity: 38,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 9,
            },
            wind: {
                speed: 3.11,
                deg: 263,
                gust: 5.14,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-05 00:00:00',
        },
        {
            dt: 1683255600,
            main: {
                temp: 17.08,
                feels_like: 15.52,
                temp_min: 17.08,
                temp_max: 17.08,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1017,
                humidity: 26,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 14,
            },
            wind: {
                speed: 4.82,
                deg: 267,
                gust: 8.54,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-05 03:00:00',
        },
        {
            dt: 1683266400,
            main: {
                temp: 21.83,
                feels_like: 20.51,
                temp_min: 21.83,
                temp_max: 21.83,
                pressure: 1028,
                sea_level: 1028,
                grnd_level: 1017,
                humidity: 17,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 22,
            },
            wind: {
                speed: 6.25,
                deg: 266,
                gust: 8.11,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-05 06:00:00',
        },
        {
            dt: 1683277200,
            main: {
                temp: 23.66,
                feels_like: 22.45,
                temp_min: 23.66,
                temp_max: 23.66,
                pressure: 1027,
                sea_level: 1027,
                grnd_level: 1016,
                humidity: 14,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 55,
            },
            wind: {
                speed: 6.45,
                deg: 266,
                gust: 8.05,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-05 09:00:00',
        },
        {
            dt: 1683288000,
            main: {
                temp: 23.36,
                feels_like: 22.14,
                temp_min: 23.36,
                temp_max: 23.36,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1015,
                humidity: 15,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'переменная облачность',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 36,
            },
            wind: {
                speed: 5.74,
                deg: 273,
                gust: 7.53,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-05 12:00:00',
        },
        {
            dt: 1683298800,
            main: {
                temp: 17.94,
                feels_like: 16.42,
                temp_min: 17.94,
                temp_max: 17.94,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1015,
                humidity: 24,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 2.72,
                deg: 268,
                gust: 3.26,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-05 15:00:00',
        },
        {
            dt: 1683309600,
            main: {
                temp: 15.24,
                feels_like: 13.55,
                temp_min: 15.24,
                temp_max: 15.24,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1015,
                humidity: 28,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02n',
                },
            ],
            clouds: {
                all: 13,
            },
            wind: {
                speed: 2.57,
                deg: 258,
                gust: 2.63,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-05 18:00:00',
        },
        {
            dt: 1683320400,
            main: {
                temp: 13.32,
                feels_like: 11.52,
                temp_min: 13.32,
                temp_max: 13.32,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1014,
                humidity: 31,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'пасмурно',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 91,
            },
            wind: {
                speed: 2.48,
                deg: 259,
                gust: 2.55,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-05 21:00:00',
        },
        {
            dt: 1683331200,
            main: {
                temp: 12,
                feels_like: 10.17,
                temp_min: 12,
                temp_max: 12,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1014,
                humidity: 35,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 68,
            },
            wind: {
                speed: 2.13,
                deg: 260,
                gust: 2.16,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-06 00:00:00',
        },
        {
            dt: 1683342000,
            main: {
                temp: 17.99,
                feels_like: 16.52,
                temp_min: 17.99,
                temp_max: 17.99,
                pressure: 1026,
                sea_level: 1026,
                grnd_level: 1014,
                humidity: 26,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 58,
            },
            wind: {
                speed: 2.24,
                deg: 246,
                gust: 3.02,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-06 03:00:00',
        },
        {
            dt: 1683352800,
            main: {
                temp: 22.66,
                feels_like: 21.43,
                temp_min: 22.66,
                temp_max: 22.66,
                pressure: 1025,
                sea_level: 1025,
                grnd_level: 1014,
                humidity: 17,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'переменная облачность',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 41,
            },
            wind: {
                speed: 3,
                deg: 249,
                gust: 4.15,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-06 06:00:00',
        },
        {
            dt: 1683363600,
            main: {
                temp: 24.54,
                feels_like: 23.42,
                temp_min: 24.54,
                temp_max: 24.54,
                pressure: 1023,
                sea_level: 1023,
                grnd_level: 1012,
                humidity: 14,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 19,
            },
            wind: {
                speed: 3.13,
                deg: 255,
                gust: 4.15,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-06 09:00:00',
        },
        {
            dt: 1683374400,
            main: {
                temp: 24.69,
                feels_like: 23.58,
                temp_min: 24.69,
                temp_max: 24.69,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1011,
                humidity: 14,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'переменная облачность',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 32,
            },
            wind: {
                speed: 2.44,
                deg: 261,
                gust: 3.56,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-06 12:00:00',
        },
        {
            dt: 1683385200,
            main: {
                temp: 19.75,
                feels_like: 18.33,
                temp_min: 19.75,
                temp_max: 19.75,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1011,
                humidity: 21,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 0.85,
                deg: 238,
                gust: 0.88,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-06 15:00:00',
        },
        {
            dt: 1683396000,
            main: {
                temp: 17.04,
                feels_like: 15.43,
                temp_min: 17.04,
                temp_max: 17.04,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1011,
                humidity: 24,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 1.44,
                deg: 207,
                gust: 1.44,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-06 18:00:00',
        },
        {
            dt: 1683406800,
            main: {
                temp: 15.14,
                feels_like: 13.36,
                temp_min: 15.14,
                temp_max: 15.14,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1011,
                humidity: 25,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01n',
                },
            ],
            clouds: {
                all: 7,
            },
            wind: {
                speed: 1.6,
                deg: 215,
                gust: 1.6,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-06 21:00:00',
        },
        {
            dt: 1683417600,
            main: {
                temp: 14.15,
                feels_like: 12.33,
                temp_min: 14.15,
                temp_max: 14.15,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1011,
                humidity: 27,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 8,
            },
            wind: {
                speed: 1.79,
                deg: 196,
                gust: 1.8,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-07 00:00:00',
        },
        {
            dt: 1683428400,
            main: {
                temp: 20.02,
                feels_like: 18.7,
                temp_min: 20.02,
                temp_max: 20.02,
                pressure: 1022,
                sea_level: 1022,
                grnd_level: 1011,
                humidity: 24,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 14,
            },
            wind: {
                speed: 2.55,
                deg: 195,
                gust: 3.4,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-07 03:00:00',
        },
        {
            dt: 1683439200,
            main: {
                temp: 25.14,
                feels_like: 24.23,
                temp_min: 25.14,
                temp_max: 25.14,
                pressure: 1021,
                sea_level: 1021,
                grnd_level: 1010,
                humidity: 20,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 11,
            },
            wind: {
                speed: 3.05,
                deg: 206,
                gust: 3.21,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-07 06:00:00',
        },
        {
            dt: 1683450000,
            main: {
                temp: 26.85,
                feels_like: 25.89,
                temp_min: 26.85,
                temp_max: 26.85,
                pressure: 1020,
                sea_level: 1020,
                grnd_level: 1009,
                humidity: 16,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'ясно',
                    icon: '01d',
                },
            ],
            clouds: {
                all: 9,
            },
            wind: {
                speed: 2.59,
                deg: 233,
                gust: 3.5,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-07 09:00:00',
        },
        {
            dt: 1683460800,
            main: {
                temp: 26.75,
                feels_like: 25.82,
                temp_min: 26.75,
                temp_max: 26.75,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 16,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04d',
                },
            ],
            clouds: {
                all: 54,
            },
            wind: {
                speed: 1.89,
                deg: 245,
                gust: 3.25,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-07 12:00:00',
        },
        {
            dt: 1683471600,
            main: {
                temp: 21.95,
                feels_like: 20.8,
                temp_min: 21.95,
                temp_max: 21.95,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 23,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'пасмурно',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 96,
            },
            wind: {
                speed: 1.06,
                deg: 109,
                gust: 1.05,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-07 15:00:00',
        },
        {
            dt: 1683482400,
            main: {
                temp: 19.18,
                feels_like: 17.88,
                temp_min: 19.18,
                temp_max: 19.18,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 28,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'облачно с прояснениями',
                    icon: '04n',
                },
            ],
            clouds: {
                all: 54,
            },
            wind: {
                speed: 3.22,
                deg: 137,
                gust: 3.72,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-07 18:00:00',
        },
        {
            dt: 1683493200,
            main: {
                temp: 17.11,
                feels_like: 15.71,
                temp_min: 17.11,
                temp_max: 17.11,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 32,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02n',
                },
            ],
            clouds: {
                all: 19,
            },
            wind: {
                speed: 2.99,
                deg: 181,
                gust: 3.48,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'n',
            },
            dt_txt: '2023-05-07 21:00:00',
        },
        {
            dt: 1683504000,
            main: {
                temp: 16.18,
                feels_like: 14.79,
                temp_min: 16.18,
                temp_max: 16.18,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 36,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 23,
            },
            wind: {
                speed: 2.78,
                deg: 192,
                gust: 3.22,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-08 00:00:00',
        },
        {
            dt: 1683514800,
            main: {
                temp: 22.28,
                feels_like: 21.32,
                temp_min: 22.28,
                temp_max: 22.28,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 29,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'переменная облачность',
                    icon: '03d',
                },
            ],
            clouds: {
                all: 31,
            },
            wind: {
                speed: 3.71,
                deg: 208,
                gust: 6.11,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-08 03:00:00',
        },
        {
            dt: 1683525600,
            main: {
                temp: 27.51,
                feels_like: 26.41,
                temp_min: 27.51,
                temp_max: 27.51,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1008,
                humidity: 20,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 22,
            },
            wind: {
                speed: 4.08,
                deg: 215,
                gust: 4.41,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-08 06:00:00',
        },
        {
            dt: 1683536400,
            main: {
                temp: 29.02,
                feels_like: 27.39,
                temp_min: 29.02,
                temp_max: 29.02,
                pressure: 1018,
                sea_level: 1018,
                grnd_level: 1007,
                humidity: 15,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'небольшая облачность',
                    icon: '02d',
                },
            ],
            clouds: {
                all: 20,
            },
            wind: {
                speed: 4.09,
                deg: 200,
                gust: 4.58,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: 'd',
            },
            dt_txt: '2023-05-08 09:00:00',
        },
    ],
    city: {
        id: 1496153,
        name: 'Омск',
        coord: {
            lat: 55,
            lon: 73.4,
        },
        country: 'RU',
        population: 1129281,
        timezone: 21600,
        sunrise: 1683069791,
        sunset: 1683125000,
    },
}
